name: Build VST Plugins

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite rodar o build manualmente na aba Actions

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B vst/build -S vst -DCMAKE_BUILD_TYPE=Release

      - name: Build Plugin
        run: |
          cmake --build vst/build --config Release --parallel 4

      - name: Upload VST3/Standalone Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NimbusReverb-Windows-Plugins
          path: |
            vst/build/**/*Nimbus*.vst3
            vst/build/**/*Nimbus*.exe
